export default {
	HYDRATEPORTFOLIO : 'HYDRATEPORTFOLIO',
	MAKETRADE : 'MAKETRADE',
	GETONEPRICE : 'GETONEPRICE',
	GETOPENINGPRICE : 'GETOPENINGPRICE',
	HANDLESOCKETMESSAGE : 'HANDLESOCKETMESSAGE',
	HANDLENEWS : 'HANDLENEWS',
	HANDLEFINANCIALS : 'HANDLEFINANCIALS',
	HANDLEHISTORICALPRICE : 'HANDLEHISTORICALPRICE',
}